### ISSUE TITLE
MetadataWranglerCoverageProvider should handle Axis 360 identifiers

### ISSUE THREAD

**Issue by skomputer** [NYPL-Simplified/circulation#189]
When attempting to refresh metadata for any Axis 360 book, the metadata wrangler always returns "202: I'm working to locate a source for this identifier" because it doesn't process Axis 360 identifiers.

**Comment by courte** [comment]
This happens when a metadata refresh is attempted because `ensure_coverage` is being used. An additional check and mapping for Axis 360 identifiers in `MetadataWranglerCoverageProvider.process_item` should sort it out.

**Comment by leonardr** [comment]
Axis 360 books are now looked up by their ISBN.
