### ISSUE TITLE
Intake from Feedbooks

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/circulation#20]
We have licensed a large catalog of books from Feedbooks.  Some Feedbooks books are derived from public domain works, but are not themselves public domain. Feedbooks catalogs are represented with OPDS and DRM is managed by LCP, which implies that ODL is also in the mix.

We need to make this catalog show up in the circulation manager, and we need to be able to transact loans against it.

[Transferred from Jira.](https://jira.nypl.org/browse/SIM-71)

**Comment by courte** [comment]
@leonardr and @aslagle have done this work on the content server, but specifically for Instant Classics and open access books. Is that enough to mark it done here?

**Comment by aslagle** [comment]
The original issue included ODL, which isn't started yet.

**Comment by leonardr** [comment]
Yes, I think we have fulfilled the original intention of this issue.
