### ISSUE TITLE
Store username and barcode in hashed form

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/circulation#24]
We need to be able to look up a Patron record given username and barcode, but (once https://jira.nypl.org/browse/SIM-59 is complete) we never need to display username or barcode unless we just got it fresh from the ILS. This means we can store Patron.username and Patron.barcode in hashed form, eliminating a bit of plaintext PII from our dataset.

[Transferred from Jira.](https://jira.nypl.org/browse/SIM-60)

**Comment by jce1028** [comment]
Given the never ending excuse to not release or classification of SimplyE as "High Risk" lets opt to be unimpeachable.

**Comment by leonardr** [comment]
Given that SimplyE has been released for a while, and this change would still cause problems for patrons, I'm re-closing this issue.
