### ISSUE TITLE
Investigate better performance for search

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#250]
Search results are much better than they used to be but they also run much more slowly. Comparing Open Ebooks's fast search to SimplyE's slow search is not terribly helpful because SimplyE's collection is 50 times larger.

See what can be done to speed up SimplyE search. If the answer is "more hardware", what kind of hardware? More RAM? More CPU? More machines in the search cluster to handle more simultaneous requests?

**Comment by aslagle** [comment]
I think we can close this now?

**Comment by leonardr** [comment]
Agreed.
