### ISSUE TITLE
StaleDataError on concurrent /loans + /borrow + /fulfill

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#275]
I fixed one source of StaleDataErrors in #269, but there's another sequence of requests that can cause them.

- Start a /loans request and fetch the remote loans
- Start and finish a /borrow request, creating a new local loan that's not in the remote loans we just got
- Start a /fulfill request, and look up the local loan
- Finish the /loans request, deleting the local loan
- Finish the /fulfill request, which tries to update the local loan and gets a StaleDataError

**Comment by leonardr** [comment]
We've decided to try and address this by having loan sync leave local loans in place if the remote hasn't heard of them but they were created within the past minute.
