### ISSUE TITLE
Within a YA or adult lane, searches should search only books for that audience

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#317]
Currently going into one of these lanes and running a search picks up books for adults. This makes it difficult for parents to justify giving the device to their kids to browse unsupervised.

**Comment by leonardr** [comment]
I don't have time to write the tests but something like this should work:

```
--- a/api/lanes.py
+++ b/api/lanes.py
@@ -191,6 +191,7 @@ def lanes_for_large_collection(_db, languages):
         _db, full_name="Young Adult Nonfiction", genres=None, fiction=False,
         include_best_sellers=True,
         include_staff_picks=True,
+        searchable=True,
         sublanes=[
             Lane(_db, full_name="YA Biography", 
                  genres=genres.Biography_Memoir,
@@ -228,6 +229,7 @@ def lanes_for_large_collection(_db, languages):
         fiction=Lane.BOTH_FICTION_AND_NONFICTION,
         include_best_sellers=True,
         include_staff_picks=True,
+        searchable=True,
         sublanes=[
             Lane(_db, full_name="Picture Books", age_range=[0,1,2,3,4],
                  genres=None, fiction=Lane.BOTH_FICTION_AND_NONFICTION,
```

**Comment by leonardr** [comment]
This doesn't really work for YA because there are two YA lanes, not one. Fortunately this isn't as big a deal for YA because teenagers aren't expected to be limited to the YA section.

**Comment by aslagle** [comment]
YA could have an invisible parent lane if we want to be able to search all YA.

**Comment by leonardr** [comment]
That's a good idea. That would also work well for searching the adult sections.

I'm going to leave this issue open to deal with that part even though the big problem has been resolved.

**Comment by courte** [comment]
I think this might have been accomplished by some savvy Elasticsearch work on @aslagle's part, but I'm not sure. It's definitely something I'd like to see on Instant Classics, so maybe I can incorporate it into that work.

**Comment by aslagle** [comment]
The elasticsearch code uses the age range and audience from the lane it's given, but only certain lanes are "searchable" and if a lane isn't searchable we go up the parents until we find one that is, and give that one to elasticsearch.

At the moment the children's lane is searchable, but the ya lanes are not, so searching a ya lane actually searches the english lane.

**Comment by leonardr** [comment]
I think we've solved this issue. I left it open because of a nice-to-have feature that we don't care about that much.
