### ISSUE TITLE
Elasticsearch server going down shouldn't affect non-search requests

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#340]
Occasionally our Elasticsearch server will go down for a few seconds. This causes a flood of errors as requests fail. For search requests this is understandable, but requests that don't touch the Elasticsearch shouldn't be affected.

**Comment by aslagle** [comment]
Is this fixed?

**Comment by leonardr** [comment]
I'm pretty sure it was fixed as a side effect of storing the search client in the `CirculationManager`. We used to try to set up a search client with every request.

Sometimes I still see search requests fail over a period of a few seconds, but it's only the search requests.
