### ISSUE TITLE
Automatic deployment to development machines

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#39]
We should be able to automatically deploy the latest code to metadata.alpha.librarysimplified.org, circulation.alpha.librarysimplified.org, and oacontent.alpha.librarysimplified.org. Since these machines are not managed by ITG, currently deployment requires SSHing in and doing a bunch of git pull commands, which is tedious.

**Comment by courte** [comment]
https://github.com/NYPL-Simplified/operations/wiki/ServerList#setting-up-git-deploy
