### ISSUE TITLE
Add a circulation event to GA that captures the "checkouts" OA content server and associated dimension

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/circulation#435]
Currently the circulation manager checkout events do not capture distribution of OA Server content in Google Analytics.  This makes it difficult to measure impact of those titles to overall circ or gauge its demand in SimplyE.  If there is any other tile of copyright information or license information that would be helpful to include (Public Domain, vs CC or Commercial Contract..

**Comment by aslagle** [comment]
I think @leonardr added the checkout event for open access content but we still need the dimension.

**Comment by leonardr** [comment]
I'm not sure what the dimension is? Is that something I can take care of or is it a Google Analytics thing?

**Comment by aslagle** [comment]
Dimensions are the things like title and author that we send to google analytics along with the event so we can analyze and filter by them. We want to add one that indicates whether the book is open access.

**Comment by aslagle** [comment]
It has to be added to google analytics in their config as well as in the circ manager.
