### ISSUE TITLE
Circulation manager should make books available immediately, and fill in metadata later

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#46]
Currently an Overdrive book that comes into the circulation manager must go through the metadata wrangler before it becomes available to patrons. If there's a problem with the connection to the metadata wrangler, the book never shows up.

There's no reason not to make the book available immediately, using the limited metadata we get from Overdrive, possibly without a cover image. This will make the circulation manager more robust in the face of communications failure.

This will require moving some code from metadata into core, and then getting circulation to use it.

**Comment by leonardr** [comment]
Looking at the code I think the same thing is true of 3M and Axis 360 books. I think I focused on Overdrive because the code framework is not even in place to make this _possible_ for Overdrive books.

My plan for dealing with this is to use existing 'presentation_ready' for books that can show up in the collection, and a new field (or a few new fields, or a CoverageRecord) for a book's relationship with the metadata wrangler.

**Comment by courte** [comment]
Related to NYPL-Simplified/server_core#51 and #58.
