### ISSUE TITLE
Related Works grouped feed breaks when Author name is listed twice in the feed.

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/circulation#497]
![image](https://cloud.githubusercontent.com/assets/5263323/26459304/03096e44-4144-11e7-9e0d-9549ee3fd8ad.png)
![image](https://cloud.githubusercontent.com/assets/5263323/26459326/10d05f92-4144-11e7-80df-1309269510b1.png)

**Comment by gioneill** [comment]
@leonardr has plans to update feeds to give each individual author a "related" ungrouped feed, in addition to one for the series, and one that will simply be "recommended".. I'm starting the client-side implementation this sprint, but this bug will likely be obsolete with these changes.

**Comment by courte** [comment]
This was fixed in NYPL-Simplified/server_core#510 when started enforcing unique author names in the feed.
