### ISSUE TITLE
Install SSL certificate on Nexus server

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#51]
The Nexus server needs an SSL certificate. We asked ITG for one and haven't heard back yet. But it turns out we can get one for free from Amazon: https://console.aws.amazon.com/acm/home?region=us-east-1#/firstrun/

Figure out how to get a cert and install it on the Nexus machine (ec2-user@52.91.251.136 ). Alternatively, look into setting up Let's Encrypt.

KeypassX contains the AWS username/password, as well as the SSH key for the Nexus machine.

**Comment by courte** [comment]
Fiiiiiinally.
