### ISSUE TITLE
Circ manager should be able to run with an invalid SIP2 integration

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#568]
Currently the SIP2 auth provider tries to connect when it's initialized, and raises a RemoteIntegrationException if it can't. This means if you configure an invalid SIP2 auth provider and restart the circ manager, you won't be able to use the admin interface to fix it.

The exception should be stored somewhere, but shouldn't break the rest of the application.

**Comment by datalogics-cgreen** [comment]
Also applies to running circulation managers that suddenly cannot connect to their ILS for various reasons.
