### ISSUE TITLE
Store location of library registry

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#576]
To register with the library registry, the circulation manager needs to know where the registry is.

The default value should be https://registry.librarysimplified.org/ and hopefully there will never be a reason to change it.

If it is changed, any Short Client Token information will have to be renegotiated.

**Comment by aslagle** [comment]
This was done in #597. It's stored as an ExternalIntegration with "discovery" as the goal, and it's created the first time you hit the admin discovery services controller.
