### ISSUE TITLE
Service area editor

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#578]
The circulation manager admin interface should have a way of editing each library's service area. This will save us the work of manually setting the service area for each library we add to the registry.

Service area is published in the Authentication for OPDS document, like so: https://github.com/NYPL-Simplified/Simplified/wiki/Authentication-For-OPDS-Extensions#service_area

There is no need to support the GeoJSON option right now. If it simplifies the interface, it may also be possible to limit circulation managers to either a US service area or `everywhere`.

**Comment by jce1028** [comment]
Is this issue not already closed? There is an admin UI for designating service area.

**Comment by leonardr** [comment]
This issue was exported to https://jira.nypl.org/browse/SIMPLY-510, and that issue is closed.
