### ISSUE TITLE
Some books show up twice in grouped feeds

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#70]
For example, Adult Nonfiction currently has the book "101 Places in Italy", Overdrive ID 25935991-0671-4910-b4da-5268710a5d53 twice, both in the Art & Design lane. Both copies are overdrive and have 2 acquisition types, epub and pdf.

**Comment by aslagle** [comment]
At first I thought it was because those books have both epub and pdf, but I found another one that doesn't. In https://circulation.librarysimplified.org/groups/eng/Young%20Adult%20Fiction, Overdrive id 1c06d7a9-afc6-4e9e-b7ea-4ee97ed7586e is there twice.

**Comment by aslagle** [comment]
This happens when the work has two or more genres, and mulitple genres are included in the same lane. "101 Places in Italy" is in both the "Art" and "Architecture" genres. In these cases there are multiple results for a single work and lane from the mv_works_editions_workgenres_datasources_identifiers query.

**Comment by leonardr** [comment]
It would be good to keep a running list of books so we don't feature the same book twice, but I don't think this is a terribly serious problem.

**Comment by leonardr** [comment]
When I rewrote the lane generator I included code that avoids repeating books in a single grouped feed whenever possible.
