### ISSUE TITLE
Add ability to fulfill Bibliotheca audiobooks.

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/circulation#762]
Use the new Bibliotheca endpoint:  
add
```
    def get_audio_fulfillment_file(self, patron_id, bibliotheca_id):
        args = dict(request_type='GetItemAudioFulfillment', item_id=bibliotheca_id, patron_id=patron_id)
        body = self.TEMPLATE % args 
        return self.request('GetItemAudioFulfillment', body, method="POST")
```
to api/bibliotheca.py

And see attached script for usage.

**Comment by daryanypl** [comment]
[bibliotheca-raw-circulation.txt](https://github.com/NYPL-Simplified/circulation/files/1441761/bibliotheca-raw-circulation.txt)

**Comment by daryanypl** [comment]
[bibliotheca-get-findaway-book-ids.txt](https://github.com/NYPL-Simplified/circulation/files/1441762/bibliotheca-get-findaway-book-ids.txt)

**Comment by leonardr** [comment]
I've implemented this on the circulation manager side.
