### ISSUE TITLE
Make Odilo circulation adapter work with the real Odilo API

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#817]
I created a test library using a sample Odilo credential. I imported the collection and attempted to borrow a book. I ran into a number of minor problems which I addressed in these two branches:

https://github.com/NYPL-Simplified/circulation/tree/odilo-fixes
https://github.com/NYPL-Simplified/server_core/tree/odilo-fixes

* Odilo's OAuth token documents (as least from this test server) send `-1` as the `expiresIn` value. The circulation manager did not handle this value specially so it believed the token had already expired.
* Odilo requires that the format for a book be set on initial checkout, but SET_DELIVERY_MECHANISM_AT was set to BaseCirculationAPI.FULFILL_STEP.
* In `checkout`, the Patron object was being sent over the wire instead of the patron's authorization identifier.

I then ran into an error I couldn't solve. I was using `test` as my patron credential, and attempting to borrow a book gave me this error:

```
{"errors":[{"id":"patronNotFound","description":"Patron 'test' not found "}]}
```

This indicates that Odilo has some way of checking whether or not a given patron identifier "really" identifies a patron of this library. Overdrive does this by cross-checking against the library's ILS system; RBdigital does this by giving the API client the power to create patron accounts. I don't understand which approach Odilo takes, and depending on the answer, some additional development work may be necessary.

I've also noticed some problems with the data. I haven't done an exhaustive test but here are the ones that jumped out at me:

* Book titles include the author name and sometimes also include the subtitle (e.g. "The People We Hate at the Wedding A Novel  / Grant Ginder")
* Author display_names are filled with sort names (e.g. "Saul, John" instead of "John Saul").
* Sometimes trailing space is present in the author name (e.g. "Saul, John ")

I need Eduardo Cepas (https://github.com/ejcepas/) to weigh in on this issue but am not able to assign this issue to him.

**Comment by ejcepas** [comment]
Ok, thank you for the errors you've corrected.

Respecting the checkout fail, indeed, you need a patron to perfom it. The patron is checked when performing the checkout and it must exists and be ok in order to perform the checkout.
We have created a test patron for you at the test environment.

Regarding the metadata, I've talked with the people in charge of contents to see if they can adjust them. But, you have to take into account that this is just a test environment.

**Comment by leonardr** [comment]
Thanks for creating a test patron. I just want to make sure I understand the general case. Let's say NYPL enters an agreement to distribute books from Odilo, and I come in with the barcode 23331094311799, asking to borrow an Odilo title. How do you determine whether 23331094311799 is a real NYPL patron? What is the thing you're checking? Is it NYPL's ILS or something else?

If the data issues I'm seeing are problems with the data loaded into the test environment, then that's fine. We'll reevaluate whether production data has the same problems.

**Comment by leonardr** [comment]
After fixing two more errors I was able to borrow a title from Odilo and retrieve an ACSM file.

1. The final URL to the ACSM file is sent by the distributor as an absolute URL, but it was being passed in to `patron_request`, which treated it as a relative URL and prepended the API root URL onto it, creating an invalid URL.
2. Numerous `format` calls were passing a Patron object as `patronId` instead of the Patron's authorization identifier -- what Odilo considers to be the patronId.

I also discovered two more problems which may be issues with the sample data:

My database shows the language of the title I checked out as 'eng', and the description is in English, but the ACSM file has it as a Spanish title. Line 457 of core/odilo.py shows that the language comes from the Odilo API, so this is most likely an error with the sample data.

If the Odilo API does not specify a language for a book (which happened in 225 of 490 cases in the sample data), line 457 of core/odilo.py needs to set a default value. A book with no language will never be shown to patrons, so even if this isn't a problem that typically happens with real data, specifying a language is useful. I don't know what the default value should be.

**Comment by ejcepas** [comment]
Respecting the login, we usually do it as OverDrive does, that is, by cross-checking against the library's ILS, which will be the NYPL's system in this case.

Regarding the metadata, I have informed to people in charge of contents about all the issues you comment, but again, please take into account that is a test environment.

**Comment by leonardr** [comment]
I've loaded real data from Santa Clara County's Odilo collection into a database and verified that two of the problems i found are still present.

First, the 'author' field associated with a book contains the author's sort name, e.g. "Gerard Bauer, Michael". This is fine, but line 446 of core/odilo.py treats it as a display name (e.g. "Michael Gerard Bauer") and tries to convert it to a sort name. It should be the other way around.

The good news is this isn't a problem with the sample data; we can fix it by changing a couple lines of code.

Second, some of the books don't have the 'language' field. For Santa Clara County 11 books don't have a language:

* The Yellow House Mystery & El misterio de la casa amarilla
* Kitten's Spring: La primavera del gatito
* La Historia De Los Mundiales 1930-2014
* Batman
* Surprise Island & La isla de las sorpresas
* Mystery Ranch & El rancho del misterio
* That's Not Fair! / ¡No Es Justo!
* The Boxcar Children & Los chicos del vagón de carga
* Mike's Mystery & El misterio de Mike
* VIDEO
* PRUEBA DRM

Some of these look like bilingual books (i.e. the same text in both Spanish and English), but that's not a reason to omit the 'language' field. There are other bilingual books in this collection that are marked as Spanish. In every case I've seen, bilingual books are assigned to the single language most useful for classification purposes. In this case that language would, I expect, be Spanish.

I'm going to address this problem by changing the client code to set 'spa' as the default language, but this should also be addressed on the server side.

I also discovered a third problem: "VIDEO" and "PRUEBA DRM" don't seem like real titles you can borrow. They seem like system entries. But PRUEBA DRM shows up as a real book you can borrow and get an ACSM file for. VIDEO shows up as a real video that you can download as MP4. So "PRUEBA DRM" will actually show up in the Santa Clara County collection, and once we support lending video, VIDEO will also show up in the collection.

If these are test or system entries, they shouldn't be sent over the wire to a client. I don't have any way to distinguish them from "real" books.

**Comment by leonardr** [comment]
If you can guarantee that "VIDEO" and "PRUEBA DRM" are the only system entries, I can hard-code the Odilo client to filter them out. It's unlikely a real work will have either of those titles. But it would be better for all of your clients, not just the circulation manager, if this data was filtered out on the server side.

**Comment by leonardr** [comment]
I'm closing this in the absence of any reports of Odilo problems after my branch of March 8th. We can open new issues with specific problems when they come up.
