### ISSUE TITLE
Deleting large collections times out

### ISSUE THREAD

**Issue by jonathangreen** [NYPL-Simplified/circulation#821]
I'm trying to delete a collection with 50k books in it and I'm seeing the delete request timeout in the logs. In the web interface, it just never deletes. 

```
Wed Jan 17 16:09:32 2018 - HARAKIRI [core 0] 172.18.0.1 - DELETE /admin/collection/2 since 1516205053
```

**Comment by leonardr** [comment]
@aslagle I would like your take on this since you were also interested recently in deleting a large collection.

One possibility is to mark the collection as deleted, remove it from all libraries, and then have a reaper script do the actual deletion.

**Comment by aslagle** [comment]
I was interested in the same problem as Jonathan - a bunch of libraries have imported the entire open-access content server and want to switch to a smaller open-access collection.

I feel like it's quite rare that you'd want to do this specific thing, but your idea would work. In general I'd also like a way to run scripts from the admin interface. So have the request return immediately but kick off a script or put it in a queue, and maybe have a way to check whether it's done yet.

**Comment by jonathangreen** [comment]
For what its worth: +1 to being able to queue things through the web interface.
