### ISSUE TITLE
Error when deleting annotation (Android)

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/circulation#952]
Android's networking library is reporting an error when deleting a bookmark, even when it's succesful on the server.

```
JSONException: "End of input at character 0 of "
```

The assumption is that it is not expecting the empty body of the response.

**Comment by leonardr** [comment]
The code here is on line 1263 of api/controller.py, in `AnnotationController.detail`, where an empty `Response` object is returned. We could be more explicit here, but an empty `Response` object has a status code of 200 and a media type of `text/html; charset=utf-8`, so there's no reason why the client should try to parse it as a JSON document. So I think the assumption that this is JSON is on the Android side.

**Comment by gioneill** [comment]
This was resolved by moving to a class in the networking library that expects a string response from the server!
